spring:
  application:
    name: springboot-backend
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
    username: root
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update